### PR TITLE
[TASK] Remove support for v11.5 and add support for v13.0

### PR DESCRIPTION
**Pull request by brotkrueml**
Additionally:
- Add PHP 8.3 to workflow matrix
- Use "ubuntu-latest" instead of "ubuntu-22.04" to avoid problems in the future
- Update "actions/checkout" to version 4
- Update dev dependencies

### CODE REVIEW

**Comment by linawolf** [comment]
@brotkrueml the tests are failing, please have a look

**Comment by brotkrueml** [comment]
@linawolf Yup, I know. It seems the "-t" option for "runTests.sh" isn't working (anymore?). Currently, don't know how to fix this, as the script hasn't changed? Maybe I will get rid of this option and let the workflow matrix provide the TYPO3 version.

**Comment by garvinhicking** [comment]
The script uses hardcoded version strings:

=~ ^(11.5|12.0|main)$ ]

If that gets adopted to 13.0 it might do?

**Comment by brotkrueml** [comment]
> The script uses hardcoded version strings:
> 
> =~ ^(11.5|12.0|main)$ ]
> 
> If that gets adopted to 13.0 it might do?

Ah okay, haven't digged into it yet. Then the solution looks pretty easy. Thanks.

**Review by linawolf — APPROVED** [review]

**Pull request merged**
